version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-livewire
    container_name: laravel-livewire-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-livewire

  db:
    image: mysql:8.0
    container_name: laravel-livewire-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-livewire

  nginx:
    image: nginx:alpine
    container_name: laravel-livewire-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel-livewire

networks:
  laravel-livewire:
    driver: bridge

volumes:
  dbdata:
    driver: local
